version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: always
    networks:
      - default
      - shared-network
    ports:
      - "3000:3000"
networks:
  shared-network:
    external: true
